version: "3.7"
services:
  app:
    restart: on-failure
    container_name: fiap-app
    build: .
    ports:
      - "${SERVER_PORT}:3000"
    depends_on:
      db:
        condition: service_healthy
    links: 
      - db
    environment:
      - DB_HOST=db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DB=${DB_NAME}
      - DB_PORT=${DB_PORT}
    volumes: 
      - .:/usr/app
    
  db:
    container_name: db-fiap-app
    platform: linux/x86_64
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "db"]
        timeout: 20s
        retries: 10
networks:
  default:
    driver: bridge
volumes: 
  db_data:
    driver: local